language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy3

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - python: pypy3

sudo: false
cache: pip
